# Generated by Django 4.1.3 on 2022-11-20 16:15

import _operator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_ID', models.IntegerField(primary_key=_operator.truediv, serialize=False)),
                ('student_name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
            ],
        ),
    ]
