# Generated by Django 4.1.3 on 2022-11-21 17:55

import _operator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_ID', models.IntegerField(primary_key=_operator.truediv, serialize=False)),
                ('admin_name', models.CharField(max_length=60)),
            ],
        ),
    ]
