# Generated by Django 4.1.3 on 2022-11-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srsapp', '0004_teaches'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teaches',
        ),
    ]
