# Generated by Django 4.1.3 on 2022-11-21 19:46

import _operator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srsapp', '0005_delete_teaches'),
    ]

    operations = [
        migrations.CreateModel(
            name='combined_scale',
            fields=[
                ('instructor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=_operator.truediv, serialize=False, to='srsapp.instructor')),
                ('academic_scale', models.IntegerField()),
                ('non_academic_scale', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='reward',
            fields=[
                ('rank', models.IntegerField(primary_key=_operator.truediv, serialize=False)),
                ('reward_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.IntegerField()),
                ('student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srsapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_ID', models.IntegerField(primary_key=_operator.truediv, serialize=False)),
                ('course_name', models.CharField(max_length=60)),
                ('instructor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srsapp.instructor')),
            ],
        ),
    ]
