# Generated by Django 4.1.3 on 2022-11-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srsapp', '0006_combined_scale_reward_performance_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combined_scale',
            name='academic_scale',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='combined_scale',
            name='non_academic_scale',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performance',
            field=models.FloatField(),
        ),
    ]
