# Generated by Django 4.1.3 on 2022-11-21 20:03

import _operator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srsapp', '0007_alter_combined_scale_academic_scale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='id',
        ),
        migrations.AlterField(
            model_name='performance',
            name='student_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=_operator.truediv, serialize=False, to='srsapp.student'),
        ),
    ]
